user:
  kafka:
    store: user-room-state-store

room:
  kafka:
    topic: room
    store: room-state-store

chat:
  kafka:
    server: localhost:9092
    topic: chat
    replicas: 1
    partitions: 1
    store: room-messages-state-store
    retention: -1
    acks: all
    retries: 10
    requestimeout: 5000
    batch: 163850
    linger: 100
    max-in-flight: 1
    client-id: apollo-chat
    group-id: apollo-chat-group
    offset: latest

spring:
  cloud:
    function:
      definition: messageStateProcessor;
    stream:
      kafka:
        streams:
          binder:
            application-id: apollo-chat
            configuration:
              spring.json.trusted.packages: '*'
              auto.commit.interval.ms: 100
              auto.offset.reset: latest
              default:
                key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value.serde: org.springframework.kafka.support.serializer.JsonSerde
      bindings:
        messageStateProcessor-in-0.destination: chat
        messageStateProcessor-in-1.destination: room
        messageStateProcessor-out-0.destination: room-state-store
server:
  port: 8083

